repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^lambda/
    -   id: ruff-format
        files: ^lambda/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy
        files: ^lambda/
        args: [--config-file=lambda/mypy.ini]
        additional_dependencies:
        - boto3-stubs[essential]
        - types-python-dateutil